<?php
$array = array(
  array('a2' => 'UM','a3' => 'UMI','name' => 'ABD Uzak Adaları','population' => '165314'),
  array('a2' => 'VI','a3' => 'VIR','name' => 'ABD Virjin Adaları','population' => '107268'),
  array('a2' => 'AF','a3' => 'AFG','name' => 'Afganistan','population' => '35530081'),
  array('a2' => 'AX','a3' => 'ALA','name' => 'Åland Adaları','population' => '0'),
  array('a2' => 'DE','a3' => 'DEU','name' => 'Almanya','population' => '82695000'),
  array('a2' => 'US','a3' => 'USA','name' => 'Amerika Birleşik Devletleri','population' => '325719178'),
  array('a2' => 'AS','a3' => 'ASM','name' => 'Amerikan Samoası','population' => '55641'),
  array('a2' => 'AD','a3' => 'AND','name' => 'Andorra','population' => '76965'),
  array('a2' => 'AO','a3' => 'AGO','name' => 'Angola','population' => '29784193'),
  array('a2' => 'AI','a3' => 'AIA','name' => 'Anguilla','population' => '0'),
  array('a2' => 'AQ','a3' => 'ATA','name' => 'Antarktika','population' => '0'),
  array('a2' => 'AG','a3' => 'ATG','name' => 'Antigua ve Barbuda','population' => '102012'),
  array('a2' => 'AR','a3' => 'ARG','name' => 'Arjantin','population' => '44271041'),
  array('a2' => 'AL','a3' => 'ALB','name' => 'Arnavutluk','population' => '2873457'),
  array('a2' => 'AW','a3' => 'ABW','name' => 'Aruba','population' => '105264'),
  array('a2' => 'AC','a3' => '','name' => 'Ascension Adası','population' => '0'),
  array('a2' => 'AU','a3' => 'AUS','name' => 'Avustralya','population' => '24598933'),
  array('a2' => 'AT','a3' => 'AUT','name' => 'Avusturya','population' => '8809212'),
  array('a2' => 'AZ','a3' => 'AZE','name' => 'Azerbaycan','population' => '9862429'),
  array('a2' => 'BS','a3' => 'BHS','name' => 'Bahamalar','population' => '395361'),
  array('a2' => 'BH','a3' => 'BHR','name' => 'Bahreyn','population' => '1492584'),
  array('a2' => 'BD','a3' => 'BGD','name' => 'Bangladeş','population' => '164669751'),
  array('a2' => 'BB','a3' => 'BRB','name' => 'Barbados','population' => '285719'),
  array('a2' => 'EH','a3' => 'ESH','name' => 'Batı Sahra','population' => '0'),
  array('a2' => 'BY','a3' => 'BLR','name' => 'Belarus','population' => '9507875'),
  array('a2' => 'BE','a3' => 'BEL','name' => 'Belçika','population' => '11372068'),
  array('a2' => 'BZ','a3' => 'BLZ','name' => 'Belize','population' => '374681'),
  array('a2' => 'BJ','a3' => 'BEN','name' => 'Benin','population' => '11175692'),
  array('a2' => 'BM','a3' => 'BMU','name' => 'Bermuda','population' => '65441'),
  array('a2' => 'AE','a3' => 'ARE','name' => 'Birleşik Arap Emirlikleri','population' => '9400145'),
  array('a2' => 'GB','a3' => 'GBR','name' => 'Birleşik Krallık','population' => '66022273'),
  array('a2' => 'UN','a3' => '','name' => 'Birleşmiş Milletler','population' => '0'),
  array('a2' => 'BO','a3' => 'BOL','name' => 'Bolivya','population' => '11051600'),
  array('a2' => 'BA','a3' => 'BIH','name' => 'Bosna-Hersek','population' => '3507017'),
  array('a2' => 'BW','a3' => 'BWA','name' => 'Botsvana','population' => '2291661'),
  array('a2' => 'BR','a3' => 'BRA','name' => 'Brezilya','population' => '209288278'),
  array('a2' => 'IO','a3' => 'IOT','name' => 'Britanya Hint Okyanusu Toprakları','population' => '0'),
  array('a2' => 'VG','a3' => 'VGB','name' => 'Britanya Virjin Adaları','population' => '31196'),
  array('a2' => 'BN','a3' => 'BRN','name' => 'Brunei','population' => '428697'),
  array('a2' => 'BG','a3' => 'BGR','name' => 'Bulgaristan','population' => '7075991'),
  array('a2' => 'BF','a3' => 'BFA','name' => 'Burkina Faso','population' => '19193382'),
  array('a2' => 'BI','a3' => 'BDI','name' => 'Burundi','population' => '10864245'),
  array('a2' => 'BT','a3' => 'BTN','name' => 'Butan','population' => '807610'),
  array('a2' => 'CV','a3' => 'CPV','name' => 'Cape Verde','population' => '546388'),
  array('a2' => 'KY','a3' => 'CYM','name' => 'Cayman Adaları','population' => '61559'),
  array('a2' => 'GI','a3' => 'GIB','name' => 'Cebelitarık','population' => '34571'),
  array('a2' => 'DZ','a3' => 'DZA','name' => 'Cezayir','population' => '41318142'),
  array('a2' => 'CX','a3' => 'CXR','name' => 'Christmas Adası','population' => '0'),
  array('a2' => 'DJ','a3' => 'DJI','name' => 'Cibuti','population' => '956985'),
  array('a2' => 'CC','a3' => 'CCK','name' => 'Cocos (Keeling) Adaları','population' => '0'),
  array('a2' => 'CK','a3' => 'COK','name' => 'Cook Adaları','population' => '0'),
  array('a2' => 'CW','a3' => 'CUW','name' => 'Curaçao','population' => '161014'),
  array('a2' => 'TD','a3' => 'TCD','name' => 'Çad','population' => '14899994'),
  array('a2' => 'CZ','a3' => 'CZE','name' => 'Çekya','population' => '10591323'),
  array('a2' => 'CN','a3' => 'CHN','name' => 'Çin','population' => '1386395000'),
  array('a2' => 'HK','a3' => 'HKG','name' => 'Çin Hong Kong ÖİB','population' => '7391700'),
  array('a2' => 'MO','a3' => 'MAC','name' => 'Çin Makao ÖİB','population' => '622567'),
  array('a2' => 'DK','a3' => 'DNK','name' => 'Danimarka','population' => '5769603'),
  array('a2' => 'DG','a3' => '','name' => 'Diego Garcia','population' => '0'),
  array('a2' => 'DO','a3' => 'DOM','name' => 'Dominik Cumhuriyeti','population' => '10766998'),
  array('a2' => 'DM','a3' => 'DMA','name' => 'Dominika','population' => '73925'),
  array('a2' => 'EC','a3' => 'ECU','name' => 'Ekvador','population' => '16624858'),
  array('a2' => 'GQ','a3' => 'GNQ','name' => 'Ekvator Ginesi','population' => '1267689'),
  array('a2' => 'SV','a3' => 'SLV','name' => 'El Salvador','population' => '6377853'),
  array('a2' => 'ID','a3' => 'IDN','name' => 'Endonezya','population' => '263991379'),
  array('a2' => 'ER','a3' => 'ERI','name' => 'Eritre','population' => '0'),
  array('a2' => 'AM','a3' => 'ARM','name' => 'Ermenistan','population' => '2930450'),
  array('a2' => 'EE','a3' => 'EST','name' => 'Estonya','population' => '1315480'),
  array('a2' => 'ET','a3' => 'ETH','name' => 'Etiyopya','population' => '104957438'),
  array('a2' => 'EZ','a3' => '','name' => 'Eurozone','population' => '0'),
  array('a2' => 'FK','a3' => 'FLK','name' => 'Falkland Adaları','population' => '0'),
  array('a2' => 'FO','a3' => 'FRO','name' => 'Faroe Adaları','population' => '49290'),
  array('a2' => 'MA','a3' => 'MAR','name' => 'Fas','population' => '35739580'),
  array('a2' => 'FJ','a3' => 'FJI','name' => 'Fiji','population' => '905502'),
  array('a2' => 'CI','a3' => 'CIV','name' => 'Fildişi Sahili','population' => '24294750'),
  array('a2' => 'PH','a3' => 'PHL','name' => 'Filipinler','population' => '104918090'),
  array('a2' => 'PS','a3' => 'PSE','name' => 'Filistin Bölgeleri','population' => '4684777'),
  array('a2' => 'FI','a3' => 'FIN','name' => 'Finlandiya','population' => '5511303'),
  array('a2' => 'FR','a3' => 'FRA','name' => 'Fransa','population' => '67118648'),
  array('a2' => 'GF','a3' => 'GUF','name' => 'Fransız Guyanası','population' => '32125'),
  array('a2' => 'TF','a3' => 'ATF','name' => 'Fransız Güney Toprakları','population' => '0'),
  array('a2' => 'PF','a3' => 'PYF','name' => 'Fransız Polinezyası','population' => '283007'),
  array('a2' => 'GA','a3' => 'GAB','name' => 'Gabon','population' => '2025137'),
  array('a2' => 'GM','a3' => 'GMB','name' => 'Gambiya','population' => '2100568'),
  array('a2' => 'GH','a3' => 'GHA','name' => 'Gana','population' => '28833629'),
  array('a2' => 'GN','a3' => 'GIN','name' => 'Gine','population' => '12717176'),
  array('a2' => 'GW','a3' => 'GNB','name' => 'Gine-Bissau','population' => '1861283'),
  array('a2' => 'GD','a3' => 'GRD','name' => 'Grenada','population' => '107825'),
  array('a2' => 'GL','a3' => 'GRL','name' => 'Grönland','population' => '56171'),
  array('a2' => 'GP','a3' => 'GLP','name' => 'Guadalupe','population' => '0'),
  array('a2' => 'GU','a3' => 'GUM','name' => 'Guam','population' => '164229'),
  array('a2' => 'GT','a3' => 'GTM','name' => 'Guatemala','population' => '16913503'),
  array('a2' => 'GG','a3' => 'GGY','name' => 'Guernsey','population' => '0'),
  array('a2' => 'GY','a3' => 'GUY','name' => 'Guyana','population' => '777859'),
  array('a2' => 'ZA','a3' => 'ZAF','name' => 'Güney Afrika','population' => '56717156'),
  array('a2' => 'GS','a3' => 'SGS','name' => 'Güney Georgia ve Güney Sandwich Adaları','population' => '1788388852'),
  array('a2' => 'KR','a3' => 'KOR','name' => 'Güney Kore','population' => '51466201'),
  array('a2' => 'SS','a3' => 'SSD','name' => 'Güney Sudan','population' => '12575714'),
  array('a2' => 'GE','a3' => 'GEO','name' => 'Gürcistan','population' => '3717100'),
  array('a2' => 'HT','a3' => 'HTI','name' => 'Haiti','population' => '10981229'),
  array('a2' => 'HR','a3' => 'HRV','name' => 'Hırvatistan','population' => '4125700'),
  array('a2' => 'IN','a3' => 'IND','name' => 'Hindistan','population' => '1339180127'),
  array('a2' => 'NL','a3' => 'NLD','name' => 'Hollanda','population' => '17132854'),
  array('a2' => 'HN','a3' => 'HND','name' => 'Honduras','population' => '9265067'),
  array('a2' => 'IQ','a3' => 'IRQ','name' => 'Irak','population' => '38274618'),
  array('a2' => 'IR','a3' => 'IRN','name' => 'İran','population' => '81162788'),
  array('a2' => 'IE','a3' => 'IRL','name' => 'İrlanda','population' => '4813608'),
  array('a2' => 'ES','a3' => 'ESP','name' => 'İspanya','population' => '46572028'),
  array('a2' => 'IL','a3' => 'ISR','name' => 'İsrail','population' => '8712400'),
  array('a2' => 'SE','a3' => 'SWE','name' => 'İsveç','population' => '10067744'),
  array('a2' => 'CH','a3' => 'CHE','name' => 'İsviçre','population' => '8466017'),
  array('a2' => 'IT','a3' => 'ITA','name' => 'İtalya','population' => '60551416'),
  array('a2' => 'IS','a3' => 'ISL','name' => 'İzlanda','population' => '341284'),
  array('a2' => 'JM','a3' => 'JAM','name' => 'Jamaika','population' => '2890299'),
  array('a2' => 'JP','a3' => 'JPN','name' => 'Japonya','population' => '126785797'),
  array('a2' => 'JE','a3' => 'JEY','name' => 'Jersey','population' => '0'),
  array('a2' => 'KH','a3' => 'KHM','name' => 'Kamboçya','population' => '16005373'),
  array('a2' => 'CM','a3' => 'CMR','name' => 'Kamerun','population' => '24053727'),
  array('a2' => 'CA','a3' => 'CAN','name' => 'Kanada','population' => '36708083'),
  array('a2' => 'IC','a3' => '','name' => 'Kanarya Adaları','population' => '0'),
  array('a2' => 'ME','a3' => 'MNE','name' => 'Karadağ','population' => '622471'),
  array('a2' => 'BQ','a3' => 'BES','name' => 'Karayip Hollanda','population' => '628059792'),
  array('a2' => 'QA','a3' => 'QAT','name' => 'Katar','population' => '2639211'),
  array('a2' => 'KZ','a3' => 'KAZ','name' => 'Kazakistan','population' => '18037646'),
  array('a2' => 'KE','a3' => 'KEN','name' => 'Kenya','population' => '49699862'),
  array('a2' => 'CY','a3' => 'CYP','name' => 'Kıbrıs','population' => '1179551'),
  array('a2' => 'KG','a3' => 'KGZ','name' => 'Kırgızistan','population' => '6201500'),
  array('a2' => 'KI','a3' => 'KIR','name' => 'Kiribati','population' => '116398'),
  array('a2' => 'CO','a3' => 'COL','name' => 'Kolombiya','population' => '49065615'),
  array('a2' => 'KM','a3' => 'COM','name' => 'Komorlar','population' => '813912'),
  array('a2' => 'CG','a3' => 'COG','name' => 'Kongo - Brazavil','population' => '5260750'),
  array('a2' => 'CD','a3' => 'COD','name' => 'Kongo - Kinşasa','population' => '81339988'),
  array('a2' => 'XK','a3' => 'XKX','name' => 'Kosova','population' => '1830700'),
  array('a2' => 'CR','a3' => 'CRI','name' => 'Kosta Rika','population' => '4905769'),
  array('a2' => 'KW','a3' => 'KWT','name' => 'Kuveyt','population' => '4136528'),
  array('a2' => 'KP','a3' => 'PRK','name' => 'Kuzey Kore','population' => '25490965'),
  array('a2' => 'MP','a3' => 'MNP','name' => 'Kuzey Mariana Adaları','population' => '55144'),
  array('a2' => 'CU','a3' => 'CUB','name' => 'Küba','population' => '11484636'),
  array('a2' => 'LA','a3' => 'LAO','name' => 'Laos','population' => '6858160'),
  array('a2' => 'LS','a3' => 'LSO','name' => 'Lesotho','population' => '2233339'),
  array('a2' => 'LV','a3' => 'LVA','name' => 'Letonya','population' => '1940740'),
  array('a2' => 'LR','a3' => 'LBR','name' => 'Liberya','population' => '4731906'),
  array('a2' => 'LY','a3' => 'LBY','name' => 'Libya','population' => '6374616'),
  array('a2' => 'LI','a3' => 'LIE','name' => 'Liechtenstein','population' => '37922'),
  array('a2' => 'LT','a3' => 'LTU','name' => 'Litvanya','population' => '2827721'),
  array('a2' => 'LB','a3' => 'LBN','name' => 'Lübnan','population' => '6082357'),
  array('a2' => 'LU','a3' => 'LUX','name' => 'Lüksemburg','population' => '599449'),
  array('a2' => 'HU','a3' => 'HUN','name' => 'Macaristan','population' => '9781127'),
  array('a2' => 'MG','a3' => 'MDG','name' => 'Madagaskar','population' => '25570895'),
  array('a2' => 'MK','a3' => 'MKD','name' => 'Makedonya','population' => '2083160'),
  array('a2' => 'MW','a3' => 'MWI','name' => 'Malavi','population' => '18622104'),
  array('a2' => 'MV','a3' => 'MDV','name' => 'Maldivler','population' => '436330'),
  array('a2' => 'MY','a3' => 'MYS','name' => 'Malezya','population' => '31624264'),
  array('a2' => 'ML','a3' => 'MLI','name' => 'Mali','population' => '18541980'),
  array('a2' => 'MT','a3' => 'MLT','name' => 'Malta','population' => '465292'),
  array('a2' => 'IM','a3' => 'IMN','name' => 'Man Adası','population' => '84287'),
  array('a2' => 'MH','a3' => 'MHL','name' => 'Marshall Adaları','population' => '53127'),
  array('a2' => 'MQ','a3' => 'MTQ','name' => 'Martinik','population' => '0'),
  array('a2' => 'MU','a3' => 'MUS','name' => 'Mauritius','population' => '1264613'),
  array('a2' => 'YT','a3' => 'MYT','name' => 'Mayotte','population' => '0'),
  array('a2' => 'MX','a3' => 'MEX','name' => 'Meksika','population' => '129163276'),
  array('a2' => 'EG','a3' => 'EGY','name' => 'Mısır','population' => '97553151'),
  array('a2' => 'FM','a3' => 'FSM','name' => 'Mikronezya','population' => '105544'),
  array('a2' => 'MN','a3' => 'MNG','name' => 'Moğolistan','population' => '3075647'),
  array('a2' => 'MD','a3' => 'MDA','name' => 'Moldova','population' => '3549750'),
  array('a2' => 'MC','a3' => 'MCO','name' => 'Monako','population' => '38695'),
  array('a2' => 'MS','a3' => 'MSR','name' => 'Montserrat','population' => '0'),
  array('a2' => 'MR','a3' => 'MRT','name' => 'Moritanya','population' => '4420184'),
  array('a2' => 'MZ','a3' => 'MOZ','name' => 'Mozambik','population' => '29668834'),
  array('a2' => 'MM','a3' => 'MMR','name' => 'Myanmar (Burma)','population' => '53370609'),
  array('a2' => 'NA','a3' => 'NAM','name' => 'Namibya','population' => '2533794'),
  array('a2' => 'NR','a3' => 'NRU','name' => 'Nauru','population' => '13649'),
  array('a2' => 'NP','a3' => 'NPL','name' => 'Nepal','population' => '29304998'),
  array('a2' => 'NE','a3' => 'NER','name' => 'Nijer','population' => '21477348'),
  array('a2' => 'NG','a3' => 'NGA','name' => 'Nijerya','population' => '190886311'),
  array('a2' => 'NI','a3' => 'NIC','name' => 'Nikaragua','population' => '6217581'),
  array('a2' => 'NU','a3' => 'NIU','name' => 'Niue','population' => '0'),
  array('a2' => 'NF','a3' => 'NFK','name' => 'Norfolk Adası','population' => '0'),
  array('a2' => 'NO','a3' => 'NOR','name' => 'Norveç','population' => '5282223'),
  array('a2' => 'CF','a3' => 'CAF','name' => 'Orta Afrika Cumhuriyeti','population' => '4659080'),
  array('a2' => 'UZ','a3' => 'UZB','name' => 'Özbekistan','population' => '32387200'),
  array('a2' => 'PK','a3' => 'PAK','name' => 'Pakistan','population' => '197015955'),
  array('a2' => 'PW','a3' => 'PLW','name' => 'Palau','population' => '21729'),
  array('a2' => 'PA','a3' => 'PAN','name' => 'Panama','population' => '4098587'),
  array('a2' => 'PG','a3' => 'PNG','name' => 'Papua Yeni Gine','population' => '8251162'),
  array('a2' => 'PY','a3' => 'PRY','name' => 'Paraguay','population' => '6811297'),
  array('a2' => 'PE','a3' => 'PER','name' => 'Peru','population' => '32165485'),
  array('a2' => 'PN','a3' => 'PCN','name' => 'Pitcairn Adaları','population' => '0'),
  array('a2' => 'PL','a3' => 'POL','name' => 'Polonya','population' => '37975841'),
  array('a2' => 'PT','a3' => 'PRT','name' => 'Portekiz','population' => '10293718'),
  array('a2' => 'PR','a3' => 'PRI','name' => 'Porto Riko','population' => '3337177'),
  array('a2' => 'RE','a3' => 'REU','name' => 'Réunion','population' => '0'),
  array('a2' => 'RO','a3' => 'ROU','name' => 'Romanya','population' => '19586539'),
  array('a2' => 'RW','a3' => 'RWA','name' => 'Ruanda','population' => '12208407'),
  array('a2' => 'RU','a3' => 'RUS','name' => 'Rusya','population' => '144495044'),
  array('a2' => 'BL','a3' => 'BLM','name' => 'Saint Barthelemy','population' => '0'),
  array('a2' => 'SH','a3' => 'SHN','name' => 'Saint Helena','population' => '0'),
  array('a2' => 'KN','a3' => 'KNA','name' => 'Saint Kitts ve Nevis','population' => '55345'),
  array('a2' => 'LC','a3' => 'LCA','name' => 'Saint Lucia','population' => '178844'),
  array('a2' => 'MF','a3' => 'MAF','name' => 'Saint Martin','population' => '32125'),
  array('a2' => 'PM','a3' => 'SPM','name' => 'Saint Pierre ve Miquelon','population' => '0'),
  array('a2' => 'VC','a3' => 'VCT','name' => 'Saint Vincent ve Grenadinler','population' => '109897'),
  array('a2' => 'WS','a3' => 'WSM','name' => 'Samoa','population' => '196440'),
  array('a2' => 'SM','a3' => 'SMR','name' => 'San Marino','population' => '33400'),
  array('a2' => 'ST','a3' => 'STP','name' => 'São Tomé ve Príncipe','population' => '204327'),
  array('a2' => 'SN','a3' => 'SEN','name' => 'Senegal','population' => '15850567'),
  array('a2' => 'EA','a3' => '','name' => 'Septe ve Melilla','population' => '0'),
  array('a2' => 'SC','a3' => 'SYC','name' => 'Seyşeller','population' => '95843'),
  array('a2' => 'RS','a3' => 'SRB','name' => 'Sırbistan','population' => '7022268'),
  array('a2' => 'SL','a3' => 'SLE','name' => 'Sierra Leone','population' => '7557212'),
  array('a2' => 'SG','a3' => 'SGP','name' => 'Singapur','population' => '5612253'),
  array('a2' => 'SX','a3' => 'SXM','name' => 'Sint Maarten','population' => '41109'),
  array('a2' => 'SK','a3' => 'SVK','name' => 'Slovakya','population' => '5439892'),
  array('a2' => 'SI','a3' => 'SVN','name' => 'Slovenya','population' => '2066748'),
  array('a2' => 'SB','a3' => 'SLB','name' => 'Solomon Adaları','population' => '611343'),
  array('a2' => 'SO','a3' => 'SOM','name' => 'Somali','population' => '14742523'),
  array('a2' => 'LK','a3' => 'LKA','name' => 'Sri Lanka','population' => '21444000'),
  array('a2' => 'SD','a3' => 'SDN','name' => 'Sudan','population' => '40533330'),
  array('a2' => 'SR','a3' => 'SUR','name' => 'Surinam','population' => '563402'),
  array('a2' => 'SY','a3' => 'SYR','name' => 'Suriye','population' => '18269868'),
  array('a2' => 'SA','a3' => 'SAU','name' => 'Suudi Arabistan','population' => '32938213'),
  array('a2' => 'SJ','a3' => 'SJM','name' => 'Svalbard ve Jan Mayen','population' => '0'),
  array('a2' => 'SZ','a3' => 'SWZ','name' => 'Svaziland','population' => '1367254'),
  array('a2' => 'CL','a3' => 'CHL','name' => 'Şili','population' => '18054726'),
  array('a2' => 'TJ','a3' => 'TJK','name' => 'Tacikistan','population' => '8921343'),
  array('a2' => 'TZ','a3' => 'TZA','name' => 'Tanzanya','population' => '57310019'),
  array('a2' => 'TH','a3' => 'THA','name' => 'Tayland','population' => '69037513'),
  array('a2' => 'TW','a3' => 'TWN','name' => 'Tayvan','population' => '0'),
  array('a2' => 'TL','a3' => 'TLS','name' => 'Timor-Leste','population' => '1296311'),
  array('a2' => 'TG','a3' => 'TGO','name' => 'Togo','population' => '7797694'),
  array('a2' => 'TK','a3' => 'TKL','name' => 'Tokelau','population' => '0'),
  array('a2' => 'TO','a3' => 'TON','name' => 'Tonga','population' => '108020'),
  array('a2' => 'TT','a3' => 'TTO','name' => 'Trinidad ve Tobago','population' => '1369125'),
  array('a2' => 'TA','a3' => '','name' => 'Tristan da Cunha','population' => '0'),
  array('a2' => 'TN','a3' => 'TUN','name' => 'Tunus','population' => '11532127'),
  array('a2' => 'TC','a3' => 'TCA','name' => 'Turks ve Caicos Adaları','population' => '35446'),
  array('a2' => 'TV','a3' => 'TUV','name' => 'Tuvalu','population' => '11192'),
  array('a2' => 'TR','a3' => 'TUR','name' => 'Türkiye','population' => '80745020'),
  array('a2' => 'TM','a3' => 'TKM','name' => 'Türkmenistan','population' => '5758075'),
  array('a2' => 'UG','a3' => 'UGA','name' => 'Uganda','population' => '42862958'),
  array('a2' => 'UA','a3' => 'UKR','name' => 'Ukrayna','population' => '44831159'),
  array('a2' => 'OM','a3' => 'OMN','name' => 'Umman','population' => '4636262'),
  array('a2' => 'UY','a3' => 'URY','name' => 'Uruguay','population' => '3456750'),
  array('a2' => 'JO','a3' => 'JOR','name' => 'Ürdün','population' => '9702353'),
  array('a2' => 'VU','a3' => 'VUT','name' => 'Vanuatu','population' => '276244'),
  array('a2' => 'VA','a3' => 'VAT','name' => 'Vatikan','population' => '0'),
  array('a2' => 'VE','a3' => 'VEN','name' => 'Venezuela','population' => '31977065'),
  array('a2' => 'VN','a3' => 'VNM','name' => 'Vietnam','population' => '95540800'),
  array('a2' => 'WF','a3' => 'WLF','name' => 'Wallis ve Futuna','population' => '0'),
  array('a2' => 'YE','a3' => 'YEM','name' => 'Yemen','population' => '28250420'),
  array('a2' => 'NC','a3' => 'NCL','name' => 'Yeni Kaledonya','population' => '280460'),
  array('a2' => 'NZ','a3' => 'NZL','name' => 'Yeni Zelanda','population' => '4793900'),
  array('a2' => 'GR','a3' => 'GRC','name' => 'Yunanistan','population' => '10760421'),
  array('a2' => 'ZM','a3' => 'ZMB','name' => 'Zambiya','population' => '17094130'),
  array('a2' => 'ZW','a3' => 'ZWE','name' => 'Zimbabve','population' => '16529904')
);
