<?php
$array = array(
  array('a2' => 'EZ','a3' => '','name' => 'Eurozone','latitude' => '-22.3674054','longitude' => '40.3290638'),
  array('a2' => 'AU','a3' => 'AUS','name' => 'Австралия','latitude' => '-27','longitude' => '133'),
  array('a2' => 'AT','a3' => 'AUT','name' => 'Австрия','latitude' => '47.33','longitude' => '13.33'),
  array('a2' => 'AZ','a3' => 'AZE','name' => 'Азербайджан','latitude' => '40.5','longitude' => '47.5'),
  array('a2' => 'AX','a3' => 'ALA','name' => 'Аландские о-ва','latitude' => '60.258878','longitude' => '19.2272767'),
  array('a2' => 'AL','a3' => 'ALB','name' => 'Албания','latitude' => '41','longitude' => '20'),
  array('a2' => 'DZ','a3' => 'DZA','name' => 'Алжир','latitude' => '28','longitude' => '3'),
  array('a2' => 'AS','a3' => 'ASM','name' => 'Американское Самоа','latitude' => '-14.33','longitude' => '-170'),
  array('a2' => 'AI','a3' => 'AIA','name' => 'Ангилья','latitude' => '18.25','longitude' => '-63.17'),
  array('a2' => 'AO','a3' => 'AGO','name' => 'Ангола','latitude' => '-12.5','longitude' => '18.5'),
  array('a2' => 'AD','a3' => 'AND','name' => 'Андорра','latitude' => '42.5','longitude' => '1.5'),
  array('a2' => 'AQ','a3' => 'ATA','name' => 'Антарктида','latitude' => '-90','longitude' => '0'),
  array('a2' => 'AG','a3' => 'ATG','name' => 'Антигуа и Барбуда','latitude' => '17.05','longitude' => '-61.8'),
  array('a2' => 'AR','a3' => 'ARG','name' => 'Аргентина','latitude' => '-34','longitude' => '-64'),
  array('a2' => 'AM','a3' => 'ARM','name' => 'Армения','latitude' => '40','longitude' => '45'),
  array('a2' => 'AW','a3' => 'ABW','name' => 'Аруба','latitude' => '12.5','longitude' => '-69.97'),
  array('a2' => 'AF','a3' => 'AFG','name' => 'Афганистан','latitude' => '33','longitude' => '65'),
  array('a2' => 'BS','a3' => 'BHS','name' => 'Багамы','latitude' => '24.25','longitude' => '-76'),
  array('a2' => 'BD','a3' => 'BGD','name' => 'Бангладеш','latitude' => '24','longitude' => '90'),
  array('a2' => 'BB','a3' => 'BRB','name' => 'Барбадос','latitude' => '13.17','longitude' => '-59.53'),
  array('a2' => 'BH','a3' => 'BHR','name' => 'Бахрейн','latitude' => '26','longitude' => '50.55'),
  array('a2' => 'BY','a3' => 'BLR','name' => 'Беларусь','latitude' => '53','longitude' => '28'),
  array('a2' => 'BZ','a3' => 'BLZ','name' => 'Белиз','latitude' => '17.25','longitude' => '-88.75'),
  array('a2' => 'BE','a3' => 'BEL','name' => 'Бельгия','latitude' => '50.83','longitude' => '4'),
  array('a2' => 'BJ','a3' => 'BEN','name' => 'Бенин','latitude' => '9.5','longitude' => '2.25'),
  array('a2' => 'BM','a3' => 'BMU','name' => 'Бермуды','latitude' => '32.33','longitude' => '-64.75'),
  array('a2' => 'BG','a3' => 'BGR','name' => 'Болгария','latitude' => '43','longitude' => '25'),
  array('a2' => 'BO','a3' => 'BOL','name' => 'Боливия','latitude' => '-17','longitude' => '-65'),
  array('a2' => 'BQ','a3' => 'BES','name' => 'Бонэйр, Синт-Эстатиус и Саба','latitude' => '12.201890','longitude' => '-68.262383'),
  array('a2' => 'BA','a3' => 'BIH','name' => 'Босния и Герцеговина','latitude' => '44','longitude' => '18'),
  array('a2' => 'BW','a3' => 'BWA','name' => 'Ботсвана','latitude' => '-22','longitude' => '24'),
  array('a2' => 'BR','a3' => 'BRA','name' => 'Бразилия','latitude' => '-10','longitude' => '-55'),
  array('a2' => 'IO','a3' => 'IOT','name' => 'Британская территория в Индийском океане','latitude' => '-6','longitude' => '71.5'),
  array('a2' => 'BN','a3' => 'BRN','name' => 'Бруней-Даруссалам','latitude' => '4.5','longitude' => '114.67'),
  array('a2' => 'BF','a3' => 'BFA','name' => 'Буркина-Фасо','latitude' => '13','longitude' => '-2'),
  array('a2' => 'BI','a3' => 'BDI','name' => 'Бурунди','latitude' => '-3.5','longitude' => '30'),
  array('a2' => 'BT','a3' => 'BTN','name' => 'Бутан','latitude' => '27.5','longitude' => '90.5'),
  array('a2' => 'VU','a3' => 'VUT','name' => 'Вануату','latitude' => '-16','longitude' => '167'),
  array('a2' => 'VA','a3' => 'VAT','name' => 'Ватикан','latitude' => '41.9','longitude' => '12.45'),
  array('a2' => 'GB','a3' => 'GBR','name' => 'Великобритания','latitude' => '54','longitude' => '-2'),
  array('a2' => 'HU','a3' => 'HUN','name' => 'Венгрия','latitude' => '47','longitude' => '20'),
  array('a2' => 'VE','a3' => 'VEN','name' => 'Венесуэла','latitude' => '8','longitude' => '-66'),
  array('a2' => 'VG','a3' => 'VGB','name' => 'Виргинские о-ва (Британские)','latitude' => '18.5','longitude' => '-64.5'),
  array('a2' => 'VI','a3' => 'VIR','name' => 'Виргинские о-ва (США)','latitude' => '18.33','longitude' => '-64.83'),
  array('a2' => 'UM','a3' => 'UMI','name' => 'Внешние малые о-ва (США)','latitude' => '19.28','longitude' => '166.6'),
  array('a2' => 'TL','a3' => 'TLS','name' => 'Восточный Тимор','latitude' => '-8.674213','longitude' => '125.882807'),
  array('a2' => 'VN','a3' => 'VNM','name' => 'Вьетнам','latitude' => '16','longitude' => '106'),
  array('a2' => 'GA','a3' => 'GAB','name' => 'Габон','latitude' => '-1','longitude' => '11.75'),
  array('a2' => 'HT','a3' => 'HTI','name' => 'Гаити','latitude' => '19','longitude' => '-72.42'),
  array('a2' => 'GY','a3' => 'GUY','name' => 'Гайана','latitude' => '5','longitude' => '-59'),
  array('a2' => 'GM','a3' => 'GMB','name' => 'Гамбия','latitude' => '13.47','longitude' => '-16.57'),
  array('a2' => 'GH','a3' => 'GHA','name' => 'Гана','latitude' => '8','longitude' => '-2'),
  array('a2' => 'GP','a3' => 'GLP','name' => 'Гваделупа','latitude' => '16.25','longitude' => '-61.58'),
  array('a2' => 'GT','a3' => 'GTM','name' => 'Гватемала','latitude' => '15.5','longitude' => '-90.25'),
  array('a2' => 'GN','a3' => 'GIN','name' => 'Гвинея','latitude' => '11','longitude' => '-10'),
  array('a2' => 'GW','a3' => 'GNB','name' => 'Гвинея-Бисау','latitude' => '12','longitude' => '-15'),
  array('a2' => 'DE','a3' => 'DEU','name' => 'Германия','latitude' => '51','longitude' => '9'),
  array('a2' => 'GG','a3' => 'GGY','name' => 'Гернси','latitude' => '49.4630442','longitude' => '-2.6581519'),
  array('a2' => 'GI','a3' => 'GIB','name' => 'Гибралтар','latitude' => '36.18','longitude' => '-5.37'),
  array('a2' => 'HN','a3' => 'HND','name' => 'Гондурас','latitude' => '15','longitude' => '-86.5'),
  array('a2' => 'HK','a3' => 'HKG','name' => 'Гонконг (специальный административный район)','latitude' => '22.25','longitude' => '114.17'),
  array('a2' => 'GD','a3' => 'GRD','name' => 'Гренада','latitude' => '12.12','longitude' => '-61.67'),
  array('a2' => 'GL','a3' => 'GRL','name' => 'Гренландия','latitude' => '72','longitude' => '-40'),
  array('a2' => 'GR','a3' => 'GRC','name' => 'Греция','latitude' => '39','longitude' => '22'),
  array('a2' => 'GE','a3' => 'GEO','name' => 'Грузия','latitude' => '42','longitude' => '43.5'),
  array('a2' => 'GU','a3' => 'GUM','name' => 'Гуам','latitude' => '13.47','longitude' => '144.78'),
  array('a2' => 'DK','a3' => 'DNK','name' => 'Дания','latitude' => '56','longitude' => '10'),
  array('a2' => 'JE','a3' => 'JEY','name' => 'Джерси','latitude' => '49.2122654','longitude' => '-2.2708329'),
  array('a2' => 'DJ','a3' => 'DJI','name' => 'Джибути','latitude' => '11.5','longitude' => '43'),
  array('a2' => 'DG','a3' => '','name' => 'Диего-Гарсия','latitude' => '-7.3432227','longitude' => '72.3588798'),
  array('a2' => 'DM','a3' => 'DMA','name' => 'Доминика','latitude' => '15.42','longitude' => '-61.33'),
  array('a2' => 'DO','a3' => 'DOM','name' => 'Доминиканская Республика','latitude' => '19','longitude' => '-70.67'),
  array('a2' => 'EG','a3' => 'EGY','name' => 'Египет','latitude' => '27','longitude' => '30'),
  array('a2' => 'ZM','a3' => 'ZMB','name' => 'Замбия','latitude' => '-15','longitude' => '30'),
  array('a2' => 'EH','a3' => 'ESH','name' => 'Западная Сахара','latitude' => '24.5','longitude' => '-13'),
  array('a2' => 'ZW','a3' => 'ZWE','name' => 'Зимбабве','latitude' => '-20','longitude' => '30'),
  array('a2' => 'IL','a3' => 'ISR','name' => 'Израиль','latitude' => '31.5','longitude' => '34.75'),
  array('a2' => 'IN','a3' => 'IND','name' => 'Индия','latitude' => '20','longitude' => '77'),
  array('a2' => 'ID','a3' => 'IDN','name' => 'Индонезия','latitude' => '-5','longitude' => '120'),
  array('a2' => 'JO','a3' => 'JOR','name' => 'Иордания','latitude' => '31','longitude' => '36'),
  array('a2' => 'IQ','a3' => 'IRQ','name' => 'Ирак','latitude' => '33','longitude' => '44'),
  array('a2' => 'IR','a3' => 'IRN','name' => 'Иран','latitude' => '32','longitude' => '53'),
  array('a2' => 'IE','a3' => 'IRL','name' => 'Ирландия','latitude' => '53','longitude' => '-8'),
  array('a2' => 'IS','a3' => 'ISL','name' => 'Исландия','latitude' => '65','longitude' => '-18'),
  array('a2' => 'ES','a3' => 'ESP','name' => 'Испания','latitude' => '40','longitude' => '-4'),
  array('a2' => 'IT','a3' => 'ITA','name' => 'Италия','latitude' => '42.83','longitude' => '12.83'),
  array('a2' => 'YE','a3' => 'YEM','name' => 'Йемен','latitude' => '15','longitude' => '48'),
  array('a2' => 'CV','a3' => 'CPV','name' => 'Кабо-Верде','latitude' => '16','longitude' => '-24'),
  array('a2' => 'KZ','a3' => 'KAZ','name' => 'Казахстан','latitude' => '48','longitude' => '68'),
  array('a2' => 'KY','a3' => 'CYM','name' => 'Каймановы о-ва','latitude' => '19.5','longitude' => '-80.5'),
  array('a2' => 'KH','a3' => 'KHM','name' => 'Камбоджа','latitude' => '13','longitude' => '105'),
  array('a2' => 'CM','a3' => 'CMR','name' => 'Камерун','latitude' => '6','longitude' => '12'),
  array('a2' => 'CA','a3' => 'CAN','name' => 'Канада','latitude' => '60','longitude' => '-95'),
  array('a2' => 'IC','a3' => '','name' => 'Канарские о-ва','latitude' => '28.4260613','longitude' => '-18.0971522'),
  array('a2' => 'QA','a3' => 'QAT','name' => 'Катар','latitude' => '25.5','longitude' => '51.25'),
  array('a2' => 'KE','a3' => 'KEN','name' => 'Кения','latitude' => '1','longitude' => '38'),
  array('a2' => 'CY','a3' => 'CYP','name' => 'Кипр','latitude' => '35','longitude' => '33'),
  array('a2' => 'KG','a3' => 'KGZ','name' => 'Киргизия','latitude' => '41','longitude' => '75'),
  array('a2' => 'KI','a3' => 'KIR','name' => 'Кирибати','latitude' => '1.42','longitude' => '173'),
  array('a2' => 'CN','a3' => 'CHN','name' => 'Китай','latitude' => '35','longitude' => '105'),
  array('a2' => 'KP','a3' => 'PRK','name' => 'КНДР','latitude' => '40','longitude' => '127'),
  array('a2' => 'CC','a3' => 'CCK','name' => 'Кокосовые о-ва','latitude' => '-12.5','longitude' => '96.83'),
  array('a2' => 'CO','a3' => 'COL','name' => 'Колумбия','latitude' => '4','longitude' => '-72'),
  array('a2' => 'KM','a3' => 'COM','name' => 'Коморы','latitude' => '-12.17','longitude' => '44.25'),
  array('a2' => 'CG','a3' => 'COG','name' => 'Конго - Браззавиль','latitude' => '-1','longitude' => '15'),
  array('a2' => 'CD','a3' => 'COD','name' => 'Конго - Киншаса','latitude' => '0','longitude' => '25'),
  array('a2' => 'XK','a3' => 'XKX','name' => 'Косово','latitude' => '42.5571984','longitude' => '19.7809767'),
  array('a2' => 'CR','a3' => 'CRI','name' => 'Коста-Рика','latitude' => '10','longitude' => '-84'),
  array('a2' => 'CI','a3' => 'CIV','name' => 'Кот-д’Ивуар','latitude' => '8','longitude' => '-5'),
  array('a2' => 'CU','a3' => 'CUB','name' => 'Куба','latitude' => '21.5','longitude' => '-80'),
  array('a2' => 'KW','a3' => 'KWT','name' => 'Кувейт','latitude' => '29.34','longitude' => '47.66'),
  array('a2' => 'CW','a3' => 'CUW','name' => 'Кюрасао','latitude' => '12.2077333','longitude' => '-69.4934829'),
  array('a2' => 'LA','a3' => 'LAO','name' => 'Лаос','latitude' => '18','longitude' => '105'),
  array('a2' => 'LV','a3' => 'LVA','name' => 'Латвия','latitude' => '57','longitude' => '25'),
  array('a2' => 'LS','a3' => 'LSO','name' => 'Лесото','latitude' => '-29.5','longitude' => '28.5'),
  array('a2' => 'LR','a3' => 'LBR','name' => 'Либерия','latitude' => '6.5','longitude' => '-9.5'),
  array('a2' => 'LB','a3' => 'LBN','name' => 'Ливан','latitude' => '33.83','longitude' => '35.83'),
  array('a2' => 'LY','a3' => 'LBY','name' => 'Ливия','latitude' => '25','longitude' => '17'),
  array('a2' => 'LT','a3' => 'LTU','name' => 'Литва','latitude' => '56','longitude' => '24'),
  array('a2' => 'LI','a3' => 'LIE','name' => 'Лихтенштейн','latitude' => '47.17','longitude' => '9.53'),
  array('a2' => 'LU','a3' => 'LUX','name' => 'Люксембург','latitude' => '49.75','longitude' => '6.17'),
  array('a2' => 'MU','a3' => 'MUS','name' => 'Маврикий','latitude' => '-20.28','longitude' => '57.55'),
  array('a2' => 'MR','a3' => 'MRT','name' => 'Мавритания','latitude' => '20','longitude' => '-12'),
  array('a2' => 'MG','a3' => 'MDG','name' => 'Мадагаскар','latitude' => '-20','longitude' => '47'),
  array('a2' => 'YT','a3' => 'MYT','name' => 'Майотта','latitude' => '-12.83','longitude' => '45.17'),
  array('a2' => 'MO','a3' => 'MAC','name' => 'Макао (специальный административный район)','latitude' => '22.17','longitude' => '113.55'),
  array('a2' => 'MK','a3' => 'MKD','name' => 'Македония','latitude' => '41.83','longitude' => '22'),
  array('a2' => 'MW','a3' => 'MWI','name' => 'Малави','latitude' => '-13.5','longitude' => '34'),
  array('a2' => 'MY','a3' => 'MYS','name' => 'Малайзия','latitude' => '2.5','longitude' => '112.5'),
  array('a2' => 'ML','a3' => 'MLI','name' => 'Мали','latitude' => '17','longitude' => '-4'),
  array('a2' => 'MV','a3' => 'MDV','name' => 'Мальдивы','latitude' => '3.25','longitude' => '73'),
  array('a2' => 'MT','a3' => 'MLT','name' => 'Мальта','latitude' => '35.83','longitude' => '14.58'),
  array('a2' => 'MA','a3' => 'MAR','name' => 'Марокко','latitude' => '32','longitude' => '-5'),
  array('a2' => 'MQ','a3' => 'MTQ','name' => 'Мартиника','latitude' => '14.67','longitude' => '-61'),
  array('a2' => 'MH','a3' => 'MHL','name' => 'Маршалловы Острова','latitude' => '9','longitude' => '168'),
  array('a2' => 'MX','a3' => 'MEX','name' => 'Мексика','latitude' => '23','longitude' => '-102'),
  array('a2' => 'MZ','a3' => 'MOZ','name' => 'Мозамбик','latitude' => '-18.25','longitude' => '35'),
  array('a2' => 'MD','a3' => 'MDA','name' => 'Молдова','latitude' => '47','longitude' => '29'),
  array('a2' => 'MC','a3' => 'MCO','name' => 'Монако','latitude' => '43.73','longitude' => '7.4'),
  array('a2' => 'MN','a3' => 'MNG','name' => 'Монголия','latitude' => '46','longitude' => '105'),
  array('a2' => 'MS','a3' => 'MSR','name' => 'Монтсеррат','latitude' => '16.75','longitude' => '-62.2'),
  array('a2' => 'MM','a3' => 'MMR','name' => 'Мьянма (Бирма)','latitude' => '22','longitude' => '98'),
  array('a2' => 'NA','a3' => 'NAM','name' => 'Намибия','latitude' => '-22','longitude' => '17'),
  array('a2' => 'NR','a3' => 'NRU','name' => 'Науру','latitude' => '-0.53','longitude' => '166.92'),
  array('a2' => 'NP','a3' => 'NPL','name' => 'Непал','latitude' => '28','longitude' => '84'),
  array('a2' => 'NE','a3' => 'NER','name' => 'Нигер','latitude' => '16','longitude' => '8'),
  array('a2' => 'NG','a3' => 'NGA','name' => 'Нигерия','latitude' => '10','longitude' => '8'),
  array('a2' => 'NL','a3' => 'NLD','name' => 'Нидерланды','latitude' => '52.5','longitude' => '5.75'),
  array('a2' => 'NI','a3' => 'NIC','name' => 'Никарагуа','latitude' => '13','longitude' => '-85'),
  array('a2' => 'NU','a3' => 'NIU','name' => 'Ниуэ','latitude' => '-19.03','longitude' => '-169.87'),
  array('a2' => 'NZ','a3' => 'NZL','name' => 'Новая Зеландия','latitude' => '-41','longitude' => '174'),
  array('a2' => 'NC','a3' => 'NCL','name' => 'Новая Каледония','latitude' => '-21.5','longitude' => '165.5'),
  array('a2' => 'NO','a3' => 'NOR','name' => 'Норвегия','latitude' => '62','longitude' => '10'),
  array('a2' => 'AC','a3' => '','name' => 'о-в Вознесения','latitude' => '-22.9856679','longitude' => '-28.5217201'),
  array('a2' => 'IM','a3' => 'IMN','name' => 'о-в Мэн','latitude' => '54.231068','longitude' => '-4.530906'),
  array('a2' => 'NF','a3' => 'NFK','name' => 'о-в Норфолк','latitude' => '-29.03','longitude' => '167.95'),
  array('a2' => 'CX','a3' => 'CXR','name' => 'о-в Рождества','latitude' => '-10.5','longitude' => '105.67'),
  array('a2' => 'SH','a3' => 'SHN','name' => 'о-в Св. Елены','latitude' => '-15.93','longitude' => '-5.7'),
  array('a2' => 'TC','a3' => 'TCA','name' => 'о-ва Тёркс и Кайкос','latitude' => '21.75','longitude' => '-71.58'),
  array('a2' => 'AE','a3' => 'ARE','name' => 'ОАЭ','latitude' => '24','longitude' => '54'),
  array('a2' => 'OM','a3' => 'OMN','name' => 'Оман','latitude' => '21','longitude' => '57'),
  array('a2' => 'UN','a3' => '','name' => 'Организация Объединенных Наций','latitude' => '','longitude' => ''),
  array('a2' => 'CK','a3' => 'COK','name' => 'Острова Кука','latitude' => '-21.23','longitude' => '-159.77'),
  array('a2' => 'PN','a3' => 'PCN','name' => 'острова Питкэрн','latitude' => '-24.373725','longitude' => '-128.327502'),
  array('a2' => 'PK','a3' => 'PAK','name' => 'Пакистан','latitude' => '30','longitude' => '70'),
  array('a2' => 'PW','a3' => 'PLW','name' => 'Палау','latitude' => '7.5','longitude' => '134.5'),
  array('a2' => 'PS','a3' => 'PSE','name' => 'Палестинские территории','latitude' => '32','longitude' => '35.25'),
  array('a2' => 'PA','a3' => 'PAN','name' => 'Панама','latitude' => '9','longitude' => '-80'),
  array('a2' => 'PG','a3' => 'PNG','name' => 'Папуа – Новая Гвинея','latitude' => '-6','longitude' => '147'),
  array('a2' => 'PY','a3' => 'PRY','name' => 'Парагвай','latitude' => '-23','longitude' => '-58'),
  array('a2' => 'PE','a3' => 'PER','name' => 'Перу','latitude' => '-10','longitude' => '-76'),
  array('a2' => 'PL','a3' => 'POL','name' => 'Польша','latitude' => '52','longitude' => '20'),
  array('a2' => 'PT','a3' => 'PRT','name' => 'Португалия','latitude' => '39.5','longitude' => '-8'),
  array('a2' => 'PR','a3' => 'PRI','name' => 'Пуэрто-Рико','latitude' => '18.25','longitude' => '-66.5'),
  array('a2' => 'KR','a3' => 'KOR','name' => 'Республика Корея','latitude' => '37','longitude' => '127.5'),
  array('a2' => 'RE','a3' => 'REU','name' => 'Реюньон','latitude' => '-21.1','longitude' => '55.6'),
  array('a2' => 'RU','a3' => 'RUS','name' => 'Россия','latitude' => '60','longitude' => '100'),
  array('a2' => 'RW','a3' => 'RWA','name' => 'Руанда','latitude' => '-2','longitude' => '30'),
  array('a2' => 'RO','a3' => 'ROU','name' => 'Румыния','latitude' => '46','longitude' => '25'),
  array('a2' => 'SV','a3' => 'SLV','name' => 'Сальвадор','latitude' => '13.83','longitude' => '-88.92'),
  array('a2' => 'WS','a3' => 'WSM','name' => 'Самоа','latitude' => '-13.58','longitude' => '-172.33'),
  array('a2' => 'SM','a3' => 'SMR','name' => 'Сан-Марино','latitude' => '43.77','longitude' => '12.42'),
  array('a2' => 'ST','a3' => 'STP','name' => 'Сан-Томе и Принсипи','latitude' => '1','longitude' => '7'),
  array('a2' => 'SA','a3' => 'SAU','name' => 'Саудовская Аравия','latitude' => '25','longitude' => '45'),
  array('a2' => 'SZ','a3' => 'SWZ','name' => 'Свазиленд','latitude' => '-26.5','longitude' => '31.5'),
  array('a2' => 'MP','a3' => 'MNP','name' => 'Северные Марианские о-ва','latitude' => '15.2','longitude' => '145.75'),
  array('a2' => 'SC','a3' => 'SYC','name' => 'Сейшельские Острова','latitude' => '-4.58','longitude' => '55.67'),
  array('a2' => 'BL','a3' => 'BLM','name' => 'Сен-Бартелеми','latitude' => '17.900403','longitude' => '-62.820297'),
  array('a2' => 'MF','a3' => 'MAF','name' => 'Сен-Мартен','latitude' => '18.074290','longitude' => '-63.045674'),
  array('a2' => 'PM','a3' => 'SPM','name' => 'Сен-Пьер и Микелон','latitude' => '46.83','longitude' => '-56.33'),
  array('a2' => 'SN','a3' => 'SEN','name' => 'Сенегал','latitude' => '14','longitude' => '-14'),
  array('a2' => 'VC','a3' => 'VCT','name' => 'Сент-Винсент и Гренадины','latitude' => '13.25','longitude' => '-61.2'),
  array('a2' => 'KN','a3' => 'KNA','name' => 'Сент-Китс и Невис','latitude' => '17.33','longitude' => '-62.75'),
  array('a2' => 'LC','a3' => 'LCA','name' => 'Сент-Люсия','latitude' => '13.88','longitude' => '-61.13'),
  array('a2' => 'RS','a3' => 'SRB','name' => 'Сербия','latitude' => '44','longitude' => '21'),
  array('a2' => 'EA','a3' => '','name' => 'Сеута и Мелилья','latitude' => '35.2862811','longitude' => '-2.9620361'),
  array('a2' => 'SG','a3' => 'SGP','name' => 'Сингапур','latitude' => '1.37','longitude' => '103.8'),
  array('a2' => 'SX','a3' => 'SXM','name' => 'Синт-Мартен','latitude' => '18.072431','longitude' => '-63.050396'),
  array('a2' => 'SY','a3' => 'SYR','name' => 'Сирия','latitude' => '35','longitude' => '38'),
  array('a2' => 'SK','a3' => 'SVK','name' => 'Словакия','latitude' => '48.67','longitude' => '19.5'),
  array('a2' => 'SI','a3' => 'SVN','name' => 'Словения','latitude' => '46','longitude' => '15'),
  array('a2' => 'US','a3' => 'USA','name' => 'Соединенные Штаты','latitude' => '38','longitude' => '-97'),
  array('a2' => 'SB','a3' => 'SLB','name' => 'Соломоновы Острова','latitude' => '-8','longitude' => '159'),
  array('a2' => 'SO','a3' => 'SOM','name' => 'Сомали','latitude' => '10','longitude' => '49'),
  array('a2' => 'SD','a3' => 'SDN','name' => 'Судан','latitude' => '15','longitude' => '30'),
  array('a2' => 'SR','a3' => 'SUR','name' => 'Суринам','latitude' => '4','longitude' => '-56'),
  array('a2' => 'SL','a3' => 'SLE','name' => 'Сьерра-Леоне','latitude' => '8.5','longitude' => '-11.5'),
  array('a2' => 'TJ','a3' => 'TJK','name' => 'Таджикистан','latitude' => '39','longitude' => '71'),
  array('a2' => 'TH','a3' => 'THA','name' => 'Таиланд','latitude' => '15','longitude' => '100'),
  array('a2' => 'TW','a3' => 'TWN','name' => 'Тайвань','latitude' => '23.5','longitude' => '121'),
  array('a2' => 'TZ','a3' => 'TZA','name' => 'Танзания','latitude' => '-6','longitude' => '35'),
  array('a2' => 'TG','a3' => 'TGO','name' => 'Того','latitude' => '8','longitude' => '1.17'),
  array('a2' => 'TK','a3' => 'TKL','name' => 'Токелау','latitude' => '-9','longitude' => '-172'),
  array('a2' => 'TO','a3' => 'TON','name' => 'Тонга','latitude' => '-20','longitude' => '-175'),
  array('a2' => 'TT','a3' => 'TTO','name' => 'Тринидад и Тобаго','latitude' => '11','longitude' => '-61'),
  array('a2' => 'TA','a3' => '','name' => 'Тристан-да-Кунья','latitude' => '-37.101683','longitude' => '12.277804'),
  array('a2' => 'TV','a3' => 'TUV','name' => 'Тувалу','latitude' => '-8','longitude' => '178'),
  array('a2' => 'TN','a3' => 'TUN','name' => 'Тунис','latitude' => '34','longitude' => '9'),
  array('a2' => 'TM','a3' => 'TKM','name' => 'Туркменистан','latitude' => '40','longitude' => '60'),
  array('a2' => 'TR','a3' => 'TUR','name' => 'Турция','latitude' => '39','longitude' => '35'),
  array('a2' => 'UG','a3' => 'UGA','name' => 'Уганда','latitude' => '1','longitude' => '32'),
  array('a2' => 'UZ','a3' => 'UZB','name' => 'Узбекистан','latitude' => '41','longitude' => '64'),
  array('a2' => 'UA','a3' => 'UKR','name' => 'Украина','latitude' => '49','longitude' => '32'),
  array('a2' => 'WF','a3' => 'WLF','name' => 'Уоллис и Футуна','latitude' => '-13.3','longitude' => '-176.2'),
  array('a2' => 'UY','a3' => 'URY','name' => 'Уругвай','latitude' => '-33','longitude' => '-56'),
  array('a2' => 'FO','a3' => 'FRO','name' => 'Фарерские о-ва','latitude' => '62','longitude' => '-7'),
  array('a2' => 'FM','a3' => 'FSM','name' => 'Федеративные Штаты Микронезии','latitude' => '6.92','longitude' => '158.25'),
  array('a2' => 'FJ','a3' => 'FJI','name' => 'Фиджи','latitude' => '-18','longitude' => '175'),
  array('a2' => 'PH','a3' => 'PHL','name' => 'Филиппины','latitude' => '13','longitude' => '122'),
  array('a2' => 'FI','a3' => 'FIN','name' => 'Финляндия','latitude' => '64','longitude' => '26'),
  array('a2' => 'FK','a3' => 'FLK','name' => 'Фолклендские о-ва','latitude' => '-51.75','longitude' => '-59'),
  array('a2' => 'FR','a3' => 'FRA','name' => 'Франция','latitude' => '46','longitude' => '2'),
  array('a2' => 'GF','a3' => 'GUF','name' => 'Французская Гвиана','latitude' => '4','longitude' => '-53'),
  array('a2' => 'PF','a3' => 'PYF','name' => 'Французская Полинезия','latitude' => '-15','longitude' => '-140'),
  array('a2' => 'TF','a3' => 'ATF','name' => 'Французские Южные территории','latitude' => '-43','longitude' => '67'),
  array('a2' => 'HR','a3' => 'HRV','name' => 'Хорватия','latitude' => '45.17','longitude' => '15.5'),
  array('a2' => 'CF','a3' => 'CAF','name' => 'ЦАР','latitude' => '7','longitude' => '21'),
  array('a2' => 'TD','a3' => 'TCD','name' => 'Чад','latitude' => '15','longitude' => '19'),
  array('a2' => 'ME','a3' => 'MNE','name' => 'Черногория','latitude' => '42','longitude' => '19'),
  array('a2' => 'CZ','a3' => 'CZE','name' => 'Чехия','latitude' => '49.75','longitude' => '15.5'),
  array('a2' => 'CL','a3' => 'CHL','name' => 'Чили','latitude' => '-30','longitude' => '-71'),
  array('a2' => 'CH','a3' => 'CHE','name' => 'Швейцария','latitude' => '47','longitude' => '8'),
  array('a2' => 'SE','a3' => 'SWE','name' => 'Швеция','latitude' => '62','longitude' => '15'),
  array('a2' => 'SJ','a3' => 'SJM','name' => 'Шпицберген и Ян-Майен','latitude' => '78','longitude' => '20'),
  array('a2' => 'LK','a3' => 'LKA','name' => 'Шри-Ланка','latitude' => '7','longitude' => '81'),
  array('a2' => 'EC','a3' => 'ECU','name' => 'Эквадор','latitude' => '-2','longitude' => '-77.5'),
  array('a2' => 'GQ','a3' => 'GNQ','name' => 'Экваториальная Гвинея','latitude' => '2','longitude' => '10'),
  array('a2' => 'ER','a3' => 'ERI','name' => 'Эритрея','latitude' => '15','longitude' => '39'),
  array('a2' => 'EE','a3' => 'EST','name' => 'Эстония','latitude' => '59','longitude' => '26'),
  array('a2' => 'ET','a3' => 'ETH','name' => 'Эфиопия','latitude' => '8','longitude' => '38'),
  array('a2' => 'ZA','a3' => 'ZAF','name' => 'ЮАР','latitude' => '-29','longitude' => '24'),
  array('a2' => 'GS','a3' => 'SGS','name' => 'Южная Георгия и Южные Сандвичевы о-ва','latitude' => '-54.5','longitude' => '-37'),
  array('a2' => 'SS','a3' => 'SSD','name' => 'Южный Судан','latitude' => '7.7660983','longitude' => '20.6491937'),
  array('a2' => 'JM','a3' => 'JAM','name' => 'Ямайка','latitude' => '18.25','longitude' => '-77.5'),
  array('a2' => 'JP','a3' => 'JPN','name' => 'Япония','latitude' => '36','longitude' => '138')
);
